In [6]:
import pandas as pd
import numpy as np

In [7]:
data=pd.read_csv(r"D:\Session Files\Fish_dataset.csv")

In [8]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [9]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [11]:
data["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [12]:
colname=[]
for x in data.columns:
    if data[x].dtypes=='object':
        colname.append(x)
colname

['Species']

In [13]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    data[x]=le.fit_transform(data[x])
    
    le_name_mapping = dict(zip(le.classes_,le.transform(le.classes_)))
    print('Feature',x)
    print('Mapping',le_name_mapping)

Feature Species
Mapping {'Bream': 0, 'Parkki': 1, 'Perch': 2, 'Pike': 3, 'Roach': 4, 'Smelt': 5, 'Whitefish': 6}


In [17]:
X=data[['Weight','Length1','Length2','Length3','Height','Width']]
y=data['Species']

In [18]:
X.shape

(159, 6)

In [19]:
y.shape

(159,)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)
X=scaler.transform(X)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [25]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                               metric='euclidean')

In [26]:
model_KNN.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [27]:
y_pred=model_KNN.predict(X_test)
print(list(zip(y_test,y_pred)))

[(2, 2), (3, 3), (4, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (4, 4), (1, 2), (0, 0), (2, 2), (0, 0), (5, 5), (2, 2), (1, 4), (4, 4), (0, 0), (5, 5), (0, 0), (3, 3), (4, 2), (1, 4), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (4, 2), (2, 2), (2, 2), (3, 2)]


In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score , classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('Classification Report')

print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('Accuracy of the model:',acc)

[[ 5  0  0  0  0  0]
 [ 0  0  1  0  2  0]
 [ 0  0 14  0  0  0]
 [ 0  0  1  2  0  0]
 [ 0  0  3  0  2  0]
 [ 0  0  0  0  0  2]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.00      0.00      0.00         3
           2       0.74      1.00      0.85        14
           3       1.00      0.67      0.80         3
           4       0.50      0.40      0.44         5
           5       1.00      1.00      1.00         2

    accuracy                           0.78        32
   macro avg       0.71      0.68      0.68        32
weighted avg       0.71      0.78      0.73        32

Accuracy of the model: 0.78125


C:\Users\gh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
